version: 1
accounts:
- name: alice
  coins:
  - 20000mars
  - 200000000umars
- name: bob
  coins:
  - 10000mars
  - 100000000umars
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5mars
  - 100000umars
validators:
- name: alice
  bonded: 100000000umars
