version: 1
accounts:
  - name: alice
    coins: ["20000token", "200000000umar"]
  - name: bob
    coins: ["10000token", "100000000umar"]
validators:
  - name: alice
    bonded: "100000000umar"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000umar"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "umar"